from layers.full import FullLayer
from layers.conv import ConvLayer
from layers.relu import ReluLayer
from layers.softmax import SoftMaxLayer
from layers.maxpool import MaxPoolLayer
from layers.cross_entropy import CrossEntropyLayer
from layers.sequential import Sequential
from layers.flatten import FlattenLayer
#from layers_template.SoftMaxLoss import SoftMaxLoss
